[package]
name = "gpt-cli-with-clap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "2.0.3", features = ["postgres"] }
clap = "3.0.0-beta.4"
dotenvy = "0.15.7"